spring.application.name=marketplace
server.port=8080
spring.datasource.url= jdbc:mysql://localhost:3306/badena_db?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username= root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Dialecto de Hibernate para Mysql
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect

# como se usa import.sql, se agrega esta línea para que Hibernate lo lea
spring.jpa.defer-datasource-initialization=true

spring.sql.init.mode=always

spring.jpa.properties.hibernate.connection.charSet=UTF-8

# Configuracion del tamaño de los archivos
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
spring.servlet.multipart.location=${java.io.tmpdir}

server.tomcat.max-parameter-count=2000
server.tomcat.max-http-form-post-size=50MB

